-- ==========================================
-- STUDENT MANAGEMENT SYSTEM
-- Oracle SQL & PL/SQL Project
-- Author: Srinidhi Gadde
-- ==========================================

-- ==========================================
-- TABLE CREATION
-- ==========================================

CREATE TABLE STUDENT (
STUDENT_ID NUMBER PRIMARY KEY,
STUDENT_NAME VARCHAR2(50) NOT NULL,
GENDER VARCHAR2(10),
PHONE VARCHAR2(15),
EMAIL VARCHAR2(50),
DEPARTMENT VARCHAR2(30)
);

CREATE TABLE COURSE (
COURSE_ID NUMBER PRIMARY KEY,
COURSE_NAME VARCHAR2(50) NOT NULL,
CREDITS NUMBER
);

CREATE TABLE ENROLLMENT (
ENROLLMENT_ID NUMBER PRIMARY KEY,
STUDENT_ID NUMBER,
COURSE_ID NUMBER,
ENROLLMENT_DATE DATE,
CONSTRAINT FK_STUDENT
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID),
CONSTRAINT FK_COURSE
FOREIGN KEY (COURSE_ID)
REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE MARKS (
MARK_ID NUMBER PRIMARY KEY,
STUDENT_ID NUMBER,
COURSE_ID NUMBER,
MARKS NUMBER,
CONSTRAINT FK_MARK_STUDENT
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID),
CONSTRAINT FK_MARK_COURSE
FOREIGN KEY (COURSE_ID)
REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE ATTENDANCE (
ATTENDANCE_ID NUMBER PRIMARY KEY,
STUDENT_ID NUMBER,
COURSE_ID NUMBER,
ATTENDANCE_PERCENT NUMBER,
CONSTRAINT FK_ATT_STUDENT
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID),
CONSTRAINT FK_ATT_COURSE
FOREIGN KEY (COURSE_ID)
REFERENCES COURSE(COURSE_ID)
);

-- ==========================================
-- SAMPLE DATA
-- ==========================================

INSERT INTO STUDENT VALUES
(101,'Rahul','Male','9876543210','[rahul@gmail.com](mailto:rahul@gmail.com)','CSE');

INSERT INTO STUDENT VALUES
(102,'Priya','Female','9876543211','[priya@gmail.com](mailto:priya@gmail.com)','ECE');

INSERT INTO STUDENT VALUES
(103,'Arjun','Male','9876543212','[arjun@gmail.com](mailto:arjun@gmail.com)','IT');

INSERT INTO COURSE VALUES
(201,'Database Management Systems',4);

INSERT INTO COURSE VALUES
(202,'Data Structures',3);

INSERT INTO COURSE VALUES
(203,'Operating Systems',4);

INSERT INTO ENROLLMENT VALUES (1,101,201,SYSDATE);
INSERT INTO ENROLLMENT VALUES (2,101,202,SYSDATE);
INSERT INTO ENROLLMENT VALUES (3,102,201,SYSDATE);
INSERT INTO ENROLLMENT VALUES (4,103,203,SYSDATE);

INSERT INTO MARKS VALUES (1,101,201,85);
INSERT INTO MARKS VALUES (2,101,202,92);
INSERT INTO MARKS VALUES (3,102,201,78);
INSERT INTO MARKS VALUES (4,103,203,88);

INSERT INTO ATTENDANCE VALUES (1,101,201,95);
INSERT INTO ATTENDANCE VALUES (2,101,202,90);
INSERT INTO ATTENDANCE VALUES (3,102,201,80);
INSERT INTO ATTENDANCE VALUES (4,103,203,92);

COMMIT;

-- ==========================================
-- PROCEDURE : ADD_STUDENT
-- ==========================================

CREATE OR REPLACE PROCEDURE ADD_STUDENT(
P_ID NUMBER,
P_NAME VARCHAR2,
P_GENDER VARCHAR2,
P_PHONE VARCHAR2,
P_EMAIL VARCHAR2,
P_DEPT VARCHAR2
)
AS
BEGIN
INSERT INTO STUDENT
VALUES(
P_ID,
P_NAME,
P_GENDER,
P_PHONE,
P_EMAIL,
P_DEPT
);

```
COMMIT;
```

END;
/

-- ==========================================
-- FUNCTION : CALCULATE_GRADE
-- ==========================================

CREATE OR REPLACE FUNCTION CALCULATE_GRADE(
P_MARKS NUMBER
)
RETURN VARCHAR2
IS
BEGIN
IF P_MARKS >= 90 THEN
RETURN 'A';
ELSIF P_MARKS >= 80 THEN
RETURN 'B';
ELSIF P_MARKS >= 70 THEN
RETURN 'C';
ELSE
RETURN 'D';
END IF;
END;
/

-- ==========================================
-- TRIGGER : CHECK_MARKS
-- ==========================================

CREATE OR REPLACE TRIGGER CHECK_MARKS
BEFORE INSERT OR UPDATE
ON MARKS
FOR EACH ROW
BEGIN
IF :NEW.MARKS < 0 THEN
RAISE_APPLICATION_ERROR(
-20001,
'Marks cannot be negative'
);
END IF;
END;
/

-- ==========================================
-- EXCEPTION HANDLING PROCEDURE
-- ==========================================

CREATE OR REPLACE PROCEDURE SAFE_ADD_STUDENT(
P_ID NUMBER,
P_NAME VARCHAR2,
P_GENDER VARCHAR2,
P_PHONE VARCHAR2,
P_EMAIL VARCHAR2,
P_DEPT VARCHAR2
)
AS
BEGIN
INSERT INTO STUDENT
VALUES(
P_ID,
P_NAME,
P_GENDER,
P_PHONE,
P_EMAIL,
P_DEPT
);

```
COMMIT;
```

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE(
'Student ID already exists'
);
END;
/

-- ==========================================
-- CURSOR PROCEDURE
-- ==========================================

CREATE OR REPLACE PROCEDURE DISPLAY_STUDENTS
AS
CURSOR STUD_CURSOR IS
SELECT STUDENT_ID,
STUDENT_NAME
FROM STUDENT;

```
V_ID STUDENT.STUDENT_ID%TYPE;
V_NAME STUDENT.STUDENT_NAME%TYPE;
```

BEGIN

```
OPEN STUD_CURSOR;

LOOP
    FETCH STUD_CURSOR
    INTO V_ID, V_NAME;

    EXIT WHEN STUD_CURSOR%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE(
        V_ID || ' - ' || V_NAME
    );

END LOOP;

CLOSE STUD_CURSOR;
```

END;
/

-- ==========================================
-- REPORT QUERY
-- ==========================================

SELECT
S.STUDENT_NAME,
C.COURSE_NAME,
M.MARKS,
A.ATTENDANCE_PERCENT
FROM STUDENT S
JOIN MARKS M
ON S.STUDENT_ID = M.STUDENT_ID
JOIN COURSE C
ON M.COURSE_ID = C.COURSE_ID
JOIN ATTENDANCE A
ON S.STUDENT_ID = A.STUDENT_ID
AND C.COURSE_ID = A.COURSE_ID;
